project_name: gowc

before:
  hooks:
    - go mod tidy

builds:
  - id: gowc
    dir: "."
    main: "."
    binary: gowc
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    goarm:
      - "7"

brews:
  - repository:
      owner: FollowTheProcess
      name: homebrew-tap
      token: "{{.Env.HOMEBREW_TAP_TOKEN}}"
    goarm: "7"
    folder: Formula
    commit_author:
      name: Tom Fleet
      email: tomfleet2018@gmail.com
    homepage: https://github.com/FollowTheProcess/gowc
    description: Toy clone of coreutils wc in Go
    license: MIT License
    install: |
      bin.install "gowc"
    test: |
      "#{bin}/gowc -version"

archives:
  - id: gowc
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

sboms:
  - id: gowc
    artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}-
        {{- .Version}}-
        {{- .Os }}-
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}.sbom

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Tag }}-dev{{ .ShortCommit }}"

changelog:
  # The changelog is handled by release drafter
  skip: true
