project_name: gowc

before:
  hooks:
    - go mod tidy

builds:
  - id: gowc
    dir: "."
    main: main.go
    binary: gowc
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64

brews:
  - goarm: "7"
    tap:
      owner: FollowTheProcess
      name: homebrew-tap
      token: "{{.Env.HOMEBREW_TAP_TOKEN}}"
    folder: Formula
    commit_author:
      name: Tom Fleet
      email: tomfleet2018@gmail.com
    homepage: https://github.com/FollowTheProcess/gowc
    description: Toy clone of coreutils wc in Go
    license: MIT License
    install: |
      bin.install "gowc"
    test: |
      "#{bin}/gowc --version"

archives:
  - id: gowc
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version}}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  # The changelog is handled by release drafter
  skip: true
